#ifndef VADERCOIN_CHAINPARAMSSEEDS_H
#define VADERCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the vadercoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x2d,0x89,0x76,0xdc,0x19,0x30,
};

static const uint8_t chainparams_seed_test[] = {
};

#endif // VADERCOIN_CHAINPARAMSSEEDS_H
